### ISSUE TITLE
Configure default path to project

### ISSUE THREAD

**Issue by samwiddowson** [tshrpl/ProjectAndWorkspaceManagement#6]
Currently creating a lot of small projects so this is exactly what I was looking for.

For a small quality of life improvement, could a configurable setting be implemented to specify a default base path for the project? The current hard-coded /projects/<full_project_path> isn't suitable for me.

**Comment by tshrpl** [comment]
sure, give me a few hours

**Comment by tshrpl** [comment]
just push a new verison [v0.1.3](https://github.com/tshrpl/ProjectAndWorkspaceManagement/tree/v0.1.3) 
for now the user defined settings file must exist even if it is empty, so [here](https://github.com/tshrpl/ProjectAndWorkspaceManagement/blob/master/messages/install.md) are some instructions

**Comment by tshrpl** [comment]
completed
